server:
  address: 127.0.0.1
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /
  #  tomcat:
  #    internal-proxies: ""
  forward-headers-strategy: native

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  default-produces-media-type: "application/json"

spring:
  data:
    rest:
      base-path: /rest
  redis:
    host: 127.0.0.1
    port: 6379
  #    password: ""
  datasource:
    url: jdbc:h2:file:./bakahome;AUTO_SERVER=TRUE
    username: demo
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
